# 01 · Baseline stage 1: train the MSE prediction models

The paper's benchmark is the two-stage "predict then optimize" approach. Stage 1, here, fits a return prediction
model by minimizing mean squared error. Stage 2 (notebook 02) sorts stocks on the predictions and builds portfolios.

Setup, following Section 4.1 and Appendix A.2:
* **Rolling windows** that move one quarter at a time: 39 months of training, 9 months of validation, then predict the
  next quarter. Two trading days before each boundary are dropped, because their labels are realized after it.
* **Models:** Linear and NN1 to NN5, with hidden layers of 32, 16, 8, 4 and 2 units; NNk uses the first k. Inputs pass
  through LayerNorm, and each hidden layer has ReLU, BatchNorm and 5% dropout.
* **Training:** Adam with learning rate 1e-3; early stopping after 10 epochs without improvement in validation MSE,
  keeping the best epoch.

Choices the paper does not report: batch size 10,000; at most 100 epochs; labels winsorized at the 0.5% and 99.5%
quantiles within each day, for training and validation only (evaluation uses raw returns); training in percent units.

`DATA_SOURCE = "synthetic"` runs the whole pipeline on simulated data.
Finished model-window pairs are saved and skipped on reruns, so a long run can be interrupted and resumed.

In [1]:
from pathlib import Path

import pandas as pd

from mlm.data import make_synthetic_panel, panel_features, rolling_windows
from mlm.train import TrainConfig, run_rolling

DATA_SOURCE = "cn"
SOURCES = {
    "cn": dict(panel="D:/ML_Markowitz_data/panel_cn", preds="D:/ML_Markowitz_data/preds/cn"),
    "synthetic": dict(panel="data_synth/panel", preds="preds/synthetic"),
}
PANEL_DIR, PRED_DIR = (Path(SOURCES[DATA_SOURCE][k]) for k in ("panel", "preds"))

MODELS = ["Linear", "NN1", "NN2", "NN3", "NN4", "NN5"]
FIRST_TEST, LAST_TEST = "2014-01-01", "2023-12-31"
FEATURES = None
CFG = TrainConfig()
CFG

TrainConfig(lr=0.001, batch_size=10000, max_epochs=100, patience=10, target_scale=100.0, winsor=(0.005, 0.995), embargo=2, data_on_device=True, use_cuda_graph=False, loss='mse', eps=0.5, weight_decay=0.0, seed=0, device='cuda')

In [2]:
if DATA_SOURCE == "synthetic" and not (PANEL_DIR / "meta.json").exists():
    make_synthetic_panel(PANEL_DIR)

features = FEATURES or panel_features(PANEL_DIR)
windows = rolling_windows(FIRST_TEST, LAST_TEST)
print(f"{len(features)} features, {len(windows)} windows")
pd.DataFrame(windows).set_index("name")

251 features, 40 windows

       train_start  val_start test_start   test_end
name
2014Q1  2010-01-01 2013-04-01 2014-01-01 2014-03-31
2014Q2  2010-04-01 2013-07-01 2014-04-01 2014-06-30
2014Q3  2010-07-01 2013-10-01 2014-07-01 2014-09-30
2014Q4  2010-10-01 2014-01-01 2014-10-01 2014-12-31
2015Q1  2011-01-01 2014-04-01 2015-01-01 2015-03-31
2015Q2  2011-04-01 2014-07-01 2015-04-01 2015-06-30
2015Q3  2011-07-01 2014-10-01 2015-07-01 2015-09-30
2015Q4  2011-10-01 2015-01-01 2015-10-01 2015-12-31
2016Q1  2012-01-01 2015-04-01 2016-01-01 2016-03-31
2016Q2  2012-04-01 2015-07-01 2016-04-01 2016-06-30
2016Q3  2012-07-01 2015-10-01 2016-07-01 2016-09-30
2016Q4  2012-10-01 2016-01-01 2016-10-01 2016-12-31
2017Q1  2013-01-01 2016-04-01 2017-01-01 2017-03-31
2017Q2  2013-04-01 2016-07-01 2017-04-01 2017-06-30
2017Q3  2013-07-01 2016-10-01 2017-07-01 2017-09-30
2017Q4  2013-10-01 2017-01-01 2017-10-01 2017-12-31
2018Q1  2014-01-01 2017-04-01 2018-01-01 2018-03-31
2018Q2  2014-04-01 2017-07-01 2018-04-01 2018-06-30
2018Q3  2014-07-01 2017-10-01 2018-07-01 2018-09-30
2018Q4  2014-10-01 2018-01-01 2018-10-01 2018-12-31
2019Q1  2015-01-01 2018-04-01 2019-01-01 2019-03-31
2019Q2  2015-04-01 2018-07-01 2019-04-01 2019-06-30
2019Q3  2015-07-01 2018-10-01 2019-07-01 2019-09-30
2019Q4  2015-10-01 2019-01-01 2019-10-01 2019-12-31
2020Q1  2016-01-01 2019-04-01 2020-01-01 2020-03-31
2020Q2  2016-04-01 2019-07-01 2020-04-01 2020-06-30
2020Q3  2016-07-01 2019-10-01 2020-07-01 2020-09-30
2020Q4  2016-10-01 2020-01-01 2020-10-01 2020-12-31
2021Q1  2017-01-01 2020-04-01 2021-01-01 2021-03-31
2021Q2  2017-04-01 2020-07-01 2021-04-01 2021-06-30
2021Q3  2017-07-01 2020-10-01 2021-07-01 2021-09-30
2021Q4  2017-10-01 2021-01-01 2021-10-01 2021-12-31
2022Q1  2018-01-01 2021-04-01 2022-01-01 2022-03-31
2022Q2  2018-04-01 2021-07-01 2022-04-01 2022-06-30
2022Q3  2018-07-01 2021-10-01 2022-07-01 2022-09-30
2022Q4  2018-10-01 2022-01-01 2022-10-01 2022-12-31
2023Q1  2019-01-01 2022-04-01 2023-01-01 2023-03-31
2023Q2  2019-04-01 2022-07-01 2023-04-01 2023-06-30
2023Q3  2019-07-01 2022-10-01 2023-07-01 2023-09-30
2023Q4  2019-10-01 2023-01-01 2023-10-01 2023-12-31

In [3]:
log = run_rolling(MODELS, PANEL_DIR, windows, PRED_DIR, CFG, features)

2014Q1 Linear epochs= 19 val_mse=5.1920 test_R2=+0.1939% (7.1s)

2014Q1 NN1    epochs= 16 val_mse=5.1905 test_R2=+0.2286% (6.1s)

2014Q1 NN2    epochs= 14 val_mse=5.1912 test_R2=+0.2429% (5.5s)

2014Q1 NN3    epochs= 14 val_mse=5.1900 test_R2=+0.2173% (6.1s)

2014Q1 NN4    epochs= 24 val_mse=5.1890 test_R2=+0.2357% (12.5s)

2014Q1 NN5    epochs= 30 val_mse=5.1899 test_R2=+0.2439% (20.5s)

2014Q2 Linear epochs= 18 val_mse=5.3023 test_R2=+0.4783% (3.3s)

2014Q2 NN1    epochs= 18 val_mse=5.3003 test_R2=+0.4022% (5.6s)

2014Q2 NN2    epochs= 19 val_mse=5.3006 test_R2=+0.3549% (7.4s)

2014Q2 NN3    epochs= 17 val_mse=5.3004 test_R2=+0.4347% (7.7s)

2014Q2 NN4    epochs= 20 val_mse=5.3009 test_R2=+0.4009% (11.0s)

2014Q2 NN5    epochs= 34 val_mse=5.2999 test_R2=+0.4711% (23.9s)

2014Q3 Linear epochs= 22 val_mse=4.6388 test_R2=+0.3090% (4.5s)

2014Q3 NN1    epochs= 22 val_mse=4.6379 test_R2=+0.2484% (7.5s)

2014Q3 NN2    epochs= 19 val_mse=4.6382 test_R2=+0.1937% (8.6s)

2014Q3 NN3    epochs= 20 val_mse=4.6388 test_R2=+0.1869% (11.0s)

2014Q3 NN4    epochs= 17 val_mse=4.6381 test_R2=+0.1962% (10.1s)

2014Q3 NN5    epochs= 31 val_mse=4.6372 test_R2=+0.2433% (19.8s)

2014Q4 Linear epochs= 25 val_mse=4.2214 test_R2=-0.3671% (4.4s)

2014Q4 NN1    epochs= 17 val_mse=4.2196 test_R2=-0.2203% (6.4s)

2014Q4 NN2    epochs= 15 val_mse=4.2209 test_R2=-0.1307% (6.4s)

2014Q4 NN3    epochs= 16 val_mse=4.2225 test_R2=-0.1468% (8.5s)

2014Q4 NN4    epochs= 16 val_mse=4.2215 test_R2=-0.0554% (10.9s)

2014Q4 NN5    epochs= 25 val_mse=4.2202 test_R2=-0.1912% (18.4s)

2015Q1 Linear epochs= 38 val_mse=4.3740 test_R2=+0.5190% (7.1s)

2015Q1 NN1    epochs= 13 val_mse=4.3733 test_R2=+0.6837% (4.5s)

2015Q1 NN2    epochs= 13 val_mse=4.3716 test_R2=+0.5694% (5.8s)

2015Q1 NN3    epochs= 13 val_mse=4.3722 test_R2=+0.5919% (6.9s)

2015Q1 NN4    epochs= 13 val_mse=4.3726 test_R2=+0.5682% (8.8s)

2015Q1 NN5    epochs= 26 val_mse=4.3734 test_R2=+0.6734% (19.7s)

2015Q2 Linear epochs= 16 val_mse=5.1746 test_R2=+0.1834% (3.0s)

2015Q2 NN1    epochs= 16 val_mse=5.1728 test_R2=+0.2083% (5.6s)

2015Q2 NN2    epochs= 16 val_mse=5.1733 test_R2=+0.1959% (6.8s)

2015Q2 NN3    epochs= 16 val_mse=5.1730 test_R2=+0.1852% (8.0s)

2015Q2 NN4    epochs= 16 val_mse=5.1727 test_R2=+0.1802% (10.4s)

2015Q2 NN5    epochs= 43 val_mse=5.1749 test_R2=+0.1197% (32.7s)

2015Q3 Linear epochs= 25 val_mse=9.2838 test_R2=+0.0647% (5.4s)

2015Q3 NN1    epochs= 16 val_mse=9.2826 test_R2=+0.0942% (6.2s)

2015Q3 NN2    epochs= 16 val_mse=9.2821 test_R2=+0.1210% (7.6s)

2015Q3 NN3    epochs= 16 val_mse=9.2843 test_R2=+0.0738% (8.6s)

2015Q3 NN4    epochs= 16 val_mse=9.2833 test_R2=+0.0832% (9.6s)

2015Q3 NN5    epochs= 36 val_mse=9.2849 test_R2=+0.1062% (25.0s)

2015Q4 Linear epochs= 14 val_mse=15.9013 test_R2=+0.4447% (6.8s)

2015Q4 NN1    epochs= 14 val_mse=15.9003 test_R2=+0.4050% (8.9s)

2015Q4 NN2    epochs= 14 val_mse=15.9016 test_R2=+0.3831% (10.4s)

2015Q4 NN3    epochs= 14 val_mse=15.9012 test_R2=+0.3466% (11.2s)

2015Q4 NN4    epochs= 15 val_mse=15.8998 test_R2=+0.3471% (12.7s)

2015Q4 NN5    epochs= 30 val_mse=15.9031 test_R2=+0.4137% (29.0s)

2016Q1 Linear epochs= 24 val_mse=17.0419 test_R2=+0.0417% (11.4s)

2016Q1 NN1    epochs= 24 val_mse=17.0330 test_R2=+0.0334% (14.7s)

2016Q1 NN2    epochs= 24 val_mse=17.0311 test_R2=+0.0115% (17.4s)

2016Q1 NN3    epochs= 24 val_mse=17.0338 test_R2=+0.0250% (20.1s)

2016Q1 NN4    epochs= 24 val_mse=17.0351 test_R2=+0.0182% (21.2s)

2016Q1 NN5    epochs= 35 val_mse=17.0378 test_R2=+0.0036% (32.6s)

2016Q2 Linear epochs= 11 val_mse=14.8185 test_R2=+0.2287% (5.4s)

2016Q2 NN1    epochs= 18 val_mse=14.8142 test_R2=+0.2145% (11.0s)

2016Q2 NN2    epochs= 18 val_mse=14.8134 test_R2=+0.1766% (12.5s)

2016Q2 NN3    epochs= 20 val_mse=14.8151 test_R2=+0.1560% (16.6s)

2016Q2 NN4    epochs= 25 val_mse=14.8111 test_R2=+0.1972% (22.9s)

2016Q2 NN5    epochs= 25 val_mse=14.8123 test_R2=+0.2523% (23.7s)

2016Q3 Linear epochs= 43 val_mse=9.0974 test_R2=+0.1088% (21.0s)

2016Q3 NN1    epochs= 14 val_mse=9.0986 test_R2=+0.1071% (9.1s)

2016Q3 NN2    epochs= 14 val_mse=9.0964 test_R2=+0.0767% (10.2s)

2016Q3 NN3    epochs= 14 val_mse=9.0962 test_R2=+0.1650% (11.8s)

2016Q3 NN4    epochs= 18 val_mse=9.0954 test_R2=+0.2175% (15.9s)

2016Q3 NN5    epochs= 31 val_mse=9.0942 test_R2=+0.1451% (29.7s)

2016Q4 Linear epochs= 16 val_mse=6.4207 test_R2=-0.0928% (7.8s)

2016Q4 NN1    epochs= 16 val_mse=6.4207 test_R2=-0.0794% (10.3s)

2016Q4 NN2    epochs= 11 val_mse=6.4208 test_R2=-0.0720% (8.0s)

2016Q4 NN3    epochs= 11 val_mse=6.4197 test_R2=-0.0266% (8.8s)

2016Q4 NN4    epochs= 14 val_mse=6.4223 test_R2=-0.0749% (12.2s)

2016Q4 NN5    epochs= 24 val_mse=6.4212 test_R2=+0.0029% (22.6s)

2017Q1 Linear epochs= 21 val_mse=3.8389 test_R2=-0.7092% (9.9s)

2017Q1 NN1    epochs= 15 val_mse=3.8416 test_R2=-0.8109% (9.5s)

2017Q1 NN2    epochs= 11 val_mse=3.8397 test_R2=-0.6744% (7.8s)

2017Q1 NN3    epochs= 11 val_mse=3.8395 test_R2=-0.5012% (8.9s)

2017Q1 NN4    epochs= 12 val_mse=3.8394 test_R2=-0.5014% (10.4s)

2017Q1 NN5    epochs= 21 val_mse=3.8401 test_R2=-0.6609% (20.1s)

2017Q2 Linear epochs= 16 val_mse=3.0670 test_R2=-0.8331% (7.7s)

2017Q2 NN1    epochs= 16 val_mse=3.0688 test_R2=-0.9086% (10.2s)

2017Q2 NN2    epochs= 11 val_mse=3.0691 test_R2=-0.6060% (8.2s)

2017Q2 NN3    epochs= 11 val_mse=3.0658 test_R2=-0.6241% (8.9s)

2017Q2 NN4    epochs= 11 val_mse=3.0662 test_R2=-0.4983% (9.9s)

2017Q2 NN5    epochs= 13 val_mse=3.0676 test_R2=-0.4755% (12.3s)

2017Q3 Linear epochs= 14 val_mse=3.4736 test_R2=-0.4325% (7.0s)

2017Q3 NN1    epochs= 14 val_mse=3.4760 test_R2=-0.5243% (8.9s)

2017Q3 NN2    epochs= 11 val_mse=3.4701 test_R2=-0.3958% (8.0s)

2017Q3 NN3    epochs= 11 val_mse=3.4694 test_R2=-0.3914% (9.0s)

2017Q3 NN4    epochs= 11 val_mse=3.4694 test_R2=-0.3536% (10.0s)

2017Q3 NN5    epochs= 15 val_mse=3.4732 test_R2=-0.4686% (14.4s)

2017Q4 Linear epochs= 17 val_mse=3.5204 test_R2=-0.8557% (8.3s)

2017Q4 NN1    epochs= 15 val_mse=3.5219 test_R2=-0.8344% (9.7s)

2017Q4 NN2    epochs= 15 val_mse=3.5203 test_R2=-0.8080% (11.0s)

2017Q4 NN3    epochs= 12 val_mse=3.5183 test_R2=-0.7712% (10.5s)

2017Q4 NN4    epochs= 12 val_mse=3.5140 test_R2=-0.7106% (10.8s)

2017Q4 NN5    epochs= 14 val_mse=3.5138 test_R2=-0.5877% (14.2s)

2018Q1 Linear epochs= 13 val_mse=3.7728 test_R2=+0.2467% (6.7s)

2018Q1 NN1    epochs= 15 val_mse=3.7744 test_R2=+0.3408% (9.8s)

2018Q1 NN2    epochs= 18 val_mse=3.7725 test_R2=+0.3463% (13.8s)

2018Q1 NN3    epochs= 11 val_mse=3.7686 test_R2=+0.0605% (9.1s)

2018Q1 NN4    epochs= 18 val_mse=3.7705 test_R2=+0.3212% (16.9s)

2018Q1 NN5    epochs= 15 val_mse=3.7688 test_R2=+0.0043% (15.1s)

2018Q2 Linear epochs= 24 val_mse=3.9881 test_R2=+0.0611% (12.9s)

2018Q2 NN1    epochs= 27 val_mse=3.9830 test_R2=+0.1034% (18.6s)

2018Q2 NN2    epochs= 20 val_mse=3.9854 test_R2=+0.1763% (15.7s)

2018Q2 NN3    epochs= 20 val_mse=3.9862 test_R2=+0.1333% (17.5s)

2018Q2 NN4    epochs= 23 val_mse=3.9847 test_R2=+0.1620% (22.4s)

2018Q2 NN5    epochs= 36 val_mse=3.9858 test_R2=+0.0956% (36.6s)

2018Q3 Linear epochs= 39 val_mse=4.6865 test_R2=+0.2167% (21.0s)

2018Q3 NN1    epochs= 25 val_mse=4.6833 test_R2=+0.3324% (18.2s)

2018Q3 NN2    epochs= 15 val_mse=4.6860 test_R2=+0.4617% (11.9s)

2018Q3 NN3    epochs= 20 val_mse=4.6869 test_R2=+0.4428% (17.5s)

2018Q3 NN4    epochs= 28 val_mse=4.6849 test_R2=+0.4296% (27.9s)

2018Q3 NN5    epochs= 28 val_mse=4.6843 test_R2=+0.4820% (29.8s)

2018Q4 Linear epochs= 22 val_mse=4.9150 test_R2=+0.2769% (12.0s)

2018Q4 NN1    epochs= 22 val_mse=4.9062 test_R2=+0.2862% (16.1s)

2018Q4 NN2    epochs= 22 val_mse=4.9050 test_R2=+0.2809% (18.2s)

2018Q4 NN3    epochs= 20 val_mse=4.9076 test_R2=+0.2443% (18.4s)

2018Q4 NN4    epochs= 20 val_mse=4.9066 test_R2=+0.3008% (20.1s)

2018Q4 NN5    epochs= 31 val_mse=4.9066 test_R2=+0.2564% (33.4s)

2019Q1 Linear epochs= 25 val_mse=5.0545 test_R2=+0.2528% (14.4s)

2019Q1 NN1    epochs= 26 val_mse=5.0467 test_R2=+0.3617% (19.9s)

2019Q1 NN2    epochs= 26 val_mse=5.0463 test_R2=+0.2865% (21.5s)

2019Q1 NN3    epochs= 22 val_mse=5.0482 test_R2=+0.3642% (20.8s)

2019Q1 NN4    epochs= 33 val_mse=5.0458 test_R2=+0.3210% (33.7s)

2019Q1 NN5    epochs= 45 val_mse=5.0450 test_R2=+0.2398% (50.1s)

2019Q2 Linear epochs= 27 val_mse=5.3309 test_R2=+0.3470% (15.5s)

2019Q2 NN1    epochs= 27 val_mse=5.3244 test_R2=+0.4267% (20.2s)

2019Q2 NN2    epochs= 18 val_mse=5.3255 test_R2=+0.5060% (15.4s)

2019Q2 NN3    epochs= 18 val_mse=5.3246 test_R2=+0.5647% (18.0s)

2019Q2 NN4    epochs= 39 val_mse=5.3250 test_R2=+0.5604% (42.2s)

2019Q2 NN5    epochs= 31 val_mse=5.3244 test_R2=+0.5372% (35.6s)

2019Q3 Linear epochs= 20 val_mse=6.0381 test_R2=+0.0715% (12.1s)

2019Q3 NN1    epochs= 20 val_mse=6.0280 test_R2=+0.1112% (15.9s)

2019Q3 NN2    epochs= 23 val_mse=6.0279 test_R2=+0.1369% (20.6s)

2019Q3 NN3    epochs= 25 val_mse=6.0283 test_R2=+0.1400% (25.0s)

2019Q3 NN4    epochs= 36 val_mse=6.0266 test_R2=+0.1559% (39.0s)

2019Q3 NN5    epochs= 33 val_mse=6.0279 test_R2=+0.1969% (38.6s)

2019Q4 Linear epochs= 16 val_mse=5.3714 test_R2=+0.0924% (10.3s)

2019Q4 NN1    epochs= 18 val_mse=5.3627 test_R2=+0.1001% (15.1s)

2019Q4 NN2    epochs= 20 val_mse=5.3624 test_R2=+0.1516% (18.7s)

2019Q4 NN3    epochs= 20 val_mse=5.3619 test_R2=+0.2051% (20.4s)

2019Q4 NN4    epochs= 25 val_mse=5.3611 test_R2=+0.1835% (28.5s)

2019Q4 NN5    epochs= 29 val_mse=5.3610 test_R2=+0.1919% (35.2s)

2020Q1 Linear epochs= 24 val_mse=4.4611 test_R2=+0.0711% (14.5s)

2020Q1 NN1    epochs= 18 val_mse=4.4532 test_R2=+0.2139% (14.8s)

2020Q1 NN2    epochs= 17 val_mse=4.4533 test_R2=+0.1916% (15.7s)

2020Q1 NN3    epochs= 17 val_mse=4.4522 test_R2=+0.1994% (17.7s)

2020Q1 NN4    epochs= 25 val_mse=4.4505 test_R2=+0.2232% (28.0s)

2020Q1 NN5    epochs= 30 val_mse=4.4515 test_R2=+0.1969% (37.0s)

2020Q2 Linear epochs= 25 val_mse=5.5038 test_R2=+0.3426% (15.6s)

2020Q2 NN1    epochs= 16 val_mse=5.4992 test_R2=+0.3572% (13.3s)

2020Q2 NN2    epochs= 16 val_mse=5.4988 test_R2=+0.3157% (15.4s)

2020Q2 NN3    epochs= 16 val_mse=5.4986 test_R2=+0.3849% (17.2s)

2020Q2 NN4    epochs= 23 val_mse=5.4982 test_R2=+0.5739% (26.4s)

2020Q2 NN5    epochs= 20 val_mse=5.4972 test_R2=+0.2749% (25.2s)

2020Q3 Linear epochs= 35 val_mse=6.0578 test_R2=+0.0791% (22.7s)

2020Q3 NN1    epochs= 15 val_mse=6.0554 test_R2=+0.1061% (12.9s)

2020Q3 NN2    epochs= 15 val_mse=6.0553 test_R2=+0.1065% (15.2s)

2020Q3 NN3    epochs= 18 val_mse=6.0537 test_R2=+0.1134% (20.3s)

2020Q3 NN4    epochs= 21 val_mse=6.0513 test_R2=+0.1840% (26.7s)

2020Q3 NN5    epochs= 30 val_mse=6.0511 test_R2=+0.1567% (40.3s)

2020Q4 Linear epochs= 31 val_mse=7.4250 test_R2=-0.0502% (21.5s)

2020Q4 NN1    epochs= 12 val_mse=7.4225 test_R2=-0.0411% (11.2s)

2020Q4 NN2    epochs= 19 val_mse=7.4204 test_R2=+0.0380% (19.4s)

2020Q4 NN3    epochs= 19 val_mse=7.4208 test_R2=+0.0520% (21.3s)

2020Q4 NN4    epochs= 24 val_mse=7.4155 test_R2=+0.1853% (33.8s)

2020Q4 NN5    epochs= 39 val_mse=7.4176 test_R2=+0.1411% (61.8s)

2021Q1 Linear epochs= 21 val_mse=5.9714 test_R2=+0.1210% (14.5s)

2021Q1 NN1    epochs= 12 val_mse=5.9703 test_R2=+0.1870% (11.2s)

2021Q1 NN2    epochs= 23 val_mse=5.9674 test_R2=+0.2134% (24.0s)

2021Q1 NN3    epochs= 23 val_mse=5.9637 test_R2=+0.2894% (26.5s)

2021Q1 NN4    epochs= 23 val_mse=5.9654 test_R2=+0.2945% (29.4s)

2021Q1 NN5    epochs= 28 val_mse=5.9675 test_R2=+0.3002% (38.5s)

2021Q2 Linear epochs= 16 val_mse=6.7008 test_R2=+0.1432% (11.6s)

2021Q2 NN1    epochs= 26 val_mse=6.6947 test_R2=+0.2464% (37.3s)

2021Q2 NN2    epochs= 16 val_mse=6.6955 test_R2=+0.2292% (46.4s)

2021Q2 NN3    epochs= 12 val_mse=6.6966 test_R2=+0.1840% (21.0s)

2021Q2 NN4    epochs= 26 val_mse=6.6950 test_R2=+0.4035% (34.7s)

2021Q2 NN5    epochs= 29 val_mse=6.6937 test_R2=+0.2997% (41.6s)

2021Q3 Linear epochs= 20 val_mse=5.9964 test_R2=-0.1399% (14.8s)

2021Q3 NN1    epochs= 28 val_mse=5.9898 test_R2=-0.1679% (26.5s)

2021Q3 NN2    epochs= 18 val_mse=5.9861 test_R2=-0.0961% (19.6s)

2021Q3 NN3    epochs= 18 val_mse=5.9831 test_R2=-0.0584% (21.9s)

2021Q3 NN4    epochs= 20 val_mse=5.9832 test_R2=-0.0843% (26.1s)

2021Q3 NN5    epochs= 28 val_mse=5.9852 test_R2=-0.0834% (40.4s)

2021Q4 Linear epochs= 12 val_mse=6.7593 test_R2=-0.1121% (9.0s)

2021Q4 NN1    epochs= 13 val_mse=6.7544 test_R2=-0.2345% (12.6s)

2021Q4 NN2    epochs= 23 val_mse=6.7494 test_R2=-0.3177% (25.9s)

2021Q4 NN3    epochs= 18 val_mse=6.7506 test_R2=-0.2684% (22.1s)

2021Q4 NN4    epochs= 20 val_mse=6.7496 test_R2=-0.2335% (26.7s)

2021Q4 NN5    epochs= 25 val_mse=6.7491 test_R2=-0.2618% (36.3s)

2022Q1 Linear epochs= 12 val_mse=6.3777 test_R2=-0.1152% (9.2s)

2022Q1 NN1    epochs= 12 val_mse=6.3751 test_R2=+0.0595% (11.9s)

2022Q1 NN2    epochs= 12 val_mse=6.3744 test_R2=+0.0826% (13.5s)

2022Q1 NN3    epochs= 14 val_mse=6.3746 test_R2=+0.1041% (17.4s)

2022Q1 NN4    epochs= 12 val_mse=6.3728 test_R2=+0.0545% (16.7s)

2022Q1 NN5    epochs= 16 val_mse=6.3735 test_R2=+0.0854% (24.6s)

2022Q2 Linear epochs= 17 val_mse=6.7719 test_R2=+0.3546% (13.3s)

2022Q2 NN1    epochs= 23 val_mse=6.7692 test_R2=+0.2738% (22.9s)

2022Q2 NN2    epochs= 11 val_mse=6.7666 test_R2=+0.3763% (12.8s)

2022Q2 NN3    epochs= 13 val_mse=6.7660 test_R2=+0.4713% (16.8s)

2022Q2 NN4    epochs= 15 val_mse=6.7666 test_R2=+0.4654% (21.5s)

2022Q2 NN5    epochs= 23 val_mse=6.7628 test_R2=+0.3976% (34.6s)

2022Q3 Linear epochs= 26 val_mse=6.9216 test_R2=+0.3092% (20.1s)

2022Q3 NN1    epochs= 13 val_mse=6.9191 test_R2=+0.2812% (13.0s)

2022Q3 NN2    epochs= 13 val_mse=6.9188 test_R2=+0.2929% (14.9s)

2022Q3 NN3    epochs= 16 val_mse=6.9189 test_R2=+0.3199% (20.8s)

2022Q3 NN4    epochs= 16 val_mse=6.9189 test_R2=+0.3395% (23.6s)

2022Q3 NN5    epochs= 21 val_mse=6.9175 test_R2=+0.2666% (32.3s)

2022Q4 Linear epochs= 40 val_mse=6.7100 test_R2=+0.1446% (30.1s)

2022Q4 NN1    epochs= 14 val_mse=6.7057 test_R2=+0.0265% (14.7s)

2022Q4 NN2    epochs= 17 val_mse=6.7058 test_R2=-0.0524% (20.3s)

2022Q4 NN3    epochs= 16 val_mse=6.7048 test_R2=-0.0345% (21.0s)

2022Q4 NN4    epochs= 22 val_mse=6.7049 test_R2=+0.0209% (31.8s)

2022Q4 NN5    epochs= 23 val_mse=6.7041 test_R2=+0.1421% (35.8s)

2023Q1 Linear epochs= 17 val_mse=6.1142 test_R2=+0.1202% (13.6s)

2023Q1 NN1    epochs= 18 val_mse=6.1104 test_R2=-0.0137% (18.9s)

2023Q1 NN2    epochs= 17 val_mse=6.1115 test_R2=+0.0186% (21.0s)

2023Q1 NN3    epochs= 19 val_mse=6.1099 test_R2=+0.0251% (25.4s)

2023Q1 NN4    epochs= 19 val_mse=6.1099 test_R2=+0.0001% (28.2s)

2023Q1 NN5    epochs= 25 val_mse=6.1108 test_R2=+0.0734% (40.7s)

2023Q2 Linear epochs= 14 val_mse=4.6760 test_R2=-0.0344% (12.0s)

2023Q2 NN1    epochs= 19 val_mse=4.6762 test_R2=-0.1281% (20.8s)

2023Q2 NN2    epochs= 19 val_mse=4.6762 test_R2=-0.1240% (23.6s)

2023Q2 NN3    epochs= 14 val_mse=4.6752 test_R2=+0.0744% (19.2s)

2023Q2 NN4    epochs= 14 val_mse=4.6752 test_R2=+0.0450% (21.0s)

2023Q2 NN5    epochs= 33 val_mse=4.6777 test_R2=-0.0472% (55.0s)

2023Q3 Linear epochs= 27 val_mse=4.4201 test_R2=+0.1936% (22.4s)

2023Q3 NN1    epochs= 14 val_mse=4.4220 test_R2=+0.1187% (16.1s)

2023Q3 NN2    epochs= 14 val_mse=4.4211 test_R2=+0.1292% (17.8s)

2023Q3 NN3    epochs= 14 val_mse=4.4222 test_R2=+0.1349% (20.7s)

2023Q3 NN4    epochs= 11 val_mse=4.4201 test_R2=+0.2270% (17.7s)

2023Q3 NN5    epochs= 12 val_mse=4.4193 test_R2=+0.0335% (20.2s)

2023Q4 Linear epochs= 13 val_mse=4.0581 test_R2=+0.1831% (11.4s)

2023Q4 NN1    epochs= 13 val_mse=4.0564 test_R2=+0.2519% (14.7s)

2023Q4 NN2    epochs= 11 val_mse=4.0562 test_R2=+0.2796% (14.2s)

2023Q4 NN3    epochs= 11 val_mse=4.0549 test_R2=+0.2270% (16.3s)

2023Q4 NN4    epochs= 12 val_mse=4.0547 test_R2=+0.3180% (19.5s)

2023Q4 NN5    epochs= 20 val_mse=4.0536 test_R2=+0.3356% (35.3s)

## Training summary (averages over windows)

In [4]:
log.groupby("model")[["epochs", "best_epoch", "val_mse", "test_r2", "seconds"]].mean().round(4)

        epochs  best_epoch  val_mse  test_r2  seconds
model
Linear  21.875      11.875   6.2362   0.0006  12.0325
NN1     17.750       7.750   6.2334   0.0007  13.5200
NN2     16.600       6.600   6.2327   0.0009  14.9275
NN3     16.350       6.350   6.2325   0.0011  15.8725
NN4     19.725       9.725   6.2317   0.0014  21.0450
NN5     27.075      17.075   6.2320   0.0012  30.8150